// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Hello

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HelloResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsHelloResponse(buf []byte, offset flatbuffers.UOffsetT) *HelloResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HelloResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *HelloResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HelloResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HelloResponse) Result(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *HelloResponse) ResultLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func HelloResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HelloResponseAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func HelloResponseStartResultVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func HelloResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
