// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Hello

import "strconv"

type RequestType int8

const (
	RequestTypeUNKNOWN  RequestType = 0
	RequestTypeGREETING RequestType = 1
	RequestTypeGOODBYE  RequestType = 2
)

var EnumNamesRequestType = map[RequestType]string{
	RequestTypeUNKNOWN:  "UNKNOWN",
	RequestTypeGREETING: "GREETING",
	RequestTypeGOODBYE:  "GOODBYE",
}

var EnumValuesRequestType = map[string]RequestType{
	"UNKNOWN":  RequestTypeUNKNOWN,
	"GREETING": RequestTypeGREETING,
	"GOODBYE":  RequestTypeGOODBYE,
}

func (v RequestType) String() string {
	if s, ok := EnumNamesRequestType[v]; ok {
		return s
	}
	return "RequestType(" + strconv.FormatInt(int64(v), 10) + ")"
}
